#build stage
FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# server stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
# Set the working directory 
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
# Use the following command to build the Docker image
# docker build -t my-nginx-app .
# Use the following command to run the Docker container
# docker run -p 80:80 my-nginx-application


